<script type='text/javascript' src='assets/js/jquery.min.js'></script>
<script type='text/javascript' src='assets/js/owl.carousel.min.js'></script>
<script type='text/javascript' src='assets/js/bootstrap.min.js'></script>
<script type='text/javascript' src='assets/js/slick.js'></script>
<script type='text/javascript' src='assets/js/wow.min.js'></script>
<script type='text/javascript' src='assets/js/jquery.mmenu.all.min.js'></script>
<script type='text/javascript' src='assets/js/lightbox.min.js'></script>
<script type='text/javascript' src='assets/js/jquery.scrollbar.js'></script>
<script type='text/javascript' src='assets/js/chosen.jquery.min.js'></script>
<script type='text/javascript' src='assets/js/jquery-ui.min.js'></script>
<script type='text/javascript' src='assets/js/jquery.bxslider.min.js'></script>
<script type='text/javascript' src='assets/js/jquery.countdown.min.js'></script>
<script type='text/javascript' src='assets/js/frontend.js'></script>
<script type='text/javascript' src='assets/js/frontend-plugin.js'></script>